name: gece
description: A sample command-line application.
version: 1.0.0+123101020

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  intl: ^0.18.1
  args: ^2.4.2
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  scr: gece